name: robustDA
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.11.7
    - anaconda
    - pip
    - numpy
    - jupyter
    - matplotlib
    - pandas
    - scikit-learn
    - netCDF4
    - cartopy
    - seaborn
    - tqdm
    